name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/emscripten
    steps:
      - uses: actions/checkout@v2
      - run: npm install prettier
      - run: npm run format:check
      - run: npm run shellcheck

  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/emscripten
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: npm install serve

      - name: Extract bench signature from git log
        run: echo "sign_ref=$(bash misc/git-log-bench-signature.sh)" >> $GITHUB_ENV

      - name: Pull docker images
        run: docker-compose pull

      - name: Build Stockfish
        run: >
          DOCKER_USER=$(id -u):$(id -g) docker-compose run emscripten
          make -C .. emscripten_build ARCH=wasm wasm_simd_post_mvp=yes

      - name: Test bench signature (Node)
        run: >
          docker-compose run -e uci_exe="node public/uci.js" -e sign_ref=${{ env.sign_ref }} node
          bash tests/bench-signature.sh

      - name: Test bench NPS (Node)
        run: >
          docker-compose run -e uci_exe="node public/uci.js" node
          bash tests/bench-nps.sh

      - name: Run server for headless testing
        run: npm run serve & sleep 3

      - name: Test bench signature (Browser)
        run: >
          docker-compose run -e uci_exe="node public/uci-puppeteer.js" -e sign_ref=${{ env.sign_ref }} browser
          bash tests/bench-signature.sh

      - name: Test bench NPS (Browser)
        run: >
          docker-compose run -e uci_exe="node public/uci-puppeteer.js" -e nps_target=250000 browser
          bash tests/bench-nps.sh

      - name: Test stress (Node)
        run: >
          docker-compose run -e uci_exe="node public/uci.js" -e n=30 node
          bash tests/stress.sh

      - name: Test stress (Browser)
        run: >
          docker-compose run -e uci_exe="node public/uci-puppeteer.js" -e n=15 browser
          bash tests/stress.sh
